version: '3.9'
services:
  postgres-server:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks: 
      - 'rebase-labs'
    
  ruby-sinatra:
    image: ruby
    command: bash -c "bundle install && rake create_tables_if_not_exist && ruby server.rb"
    working_dir: /app
    networks:
      - 'rebase-labs'
    volumes:
      - .:/app
      - labs-gems:/usr/local/bundle
    ports:
      - "3000:3000"

networks:
  rebase-labs:

volumes:
  labs-gems: